
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ScrollPaneConstants;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class MainView extends javax.swing.JFrame {

    Connector connector = new Connector();
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        bodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnTampil = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        listPanel = new javax.swing.JPanel();
        TambahData = new javax.swing.JPanel();
        JtambahData = new javax.swing.JLabel();
        lJudulBuku = new javax.swing.JLabel();
        btnTambahData = new javax.swing.JButton();
        lPenulisBuku = new javax.swing.JLabel();
        lGenreBuku = new javax.swing.JLabel();
        lPenerbutBuku = new javax.swing.JLabel();
        lLokasiBuku = new javax.swing.JLabel();
        lStokBuku = new javax.swing.JLabel();
        tfJudul = new javax.swing.JTextField();
        tfGenre = new javax.swing.JTextField();
        tfPenulis = new javax.swing.JTextField();
        tfPenerbit = new javax.swing.JTextField();
        tfLokasi = new javax.swing.JTextField();
        tfStok = new javax.swing.JTextField();
        tfId = new javax.swing.JTextField();
        UbahData = new javax.swing.JPanel();
        JubahData = new javax.swing.JLabel();
        idUbah = new javax.swing.JLabel();
        tfidUbah = new javax.swing.JTextField();
        btnidUbah = new javax.swing.JButton();
        UbahData2 = new javax.swing.JPanel();
        btnUbahData = new javax.swing.JButton();
        tfStokUbah = new javax.swing.JTextField();
        lStokBukuUbah = new javax.swing.JLabel();
        lLokasiBukuUbah = new javax.swing.JLabel();
        tfLokasiUbah = new javax.swing.JTextField();
        tfPenerbitUbah = new javax.swing.JTextField();
        lPenerbitBukuUbah = new javax.swing.JLabel();
        tfPenulisUbah = new javax.swing.JTextField();
        lPenulisBukuUbah = new javax.swing.JLabel();
        lGenreBukuUbah = new javax.swing.JLabel();
        tfGenreUbah = new javax.swing.JTextField();
        tfJudulUbah = new javax.swing.JTextField();
        lJudulBukuUbah = new javax.swing.JLabel();
        JubahData1 = new javax.swing.JLabel();
        HapusData = new javax.swing.JPanel();
        JhapusData = new javax.swing.JLabel();
        btnidHapus = new javax.swing.JButton();
        tfidHapus = new javax.swing.JTextField();
        idHapus = new javax.swing.JLabel();
        CariData = new javax.swing.JPanel();
        JcariData = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TampilData = new javax.swing.JPanel();
        JlistData1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        judulBackground = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perpustakaan Latief");

        bodyPanel.setBackground(new java.awt.Color(108, 92, 231));
        bodyPanel.setPreferredSize(new java.awt.Dimension(951, 551));

        menuPanel.setBackground(new java.awt.Color(162, 155, 254));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnTampil.setText("Tampilkan Semua");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        listPanel.setBackground(new java.awt.Color(162, 155, 254));
        listPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        listPanel.setLayout(new java.awt.CardLayout());

        JtambahData.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JtambahData.setForeground(new java.awt.Color(51, 51, 51));
        JtambahData.setText("TAMBAH DATA KE : ");

        lJudulBuku.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        lJudulBuku.setText("Judul Buku");

        btnTambahData.setText("Tambah Data");
        btnTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDataActionPerformed(evt);
            }
        });

        lPenulisBuku.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        lPenulisBuku.setText("Penulis Buku");

        lGenreBuku.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        lGenreBuku.setText("Genre Buku");

        lPenerbutBuku.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        lPenerbutBuku.setText("Penerbit Buku");

        lLokasiBuku.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        lLokasiBuku.setText("Lokasi Buku");

        lStokBuku.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        lStokBuku.setText("Stok Buku");

        tfJudul.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tfJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJudulActionPerformed(evt);
            }
        });

        tfGenre.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tfGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGenreActionPerformed(evt);
            }
        });

        tfPenulis.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        tfPenerbit.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        tfLokasi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        tfStok.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TambahDataLayout = new javax.swing.GroupLayout(TambahData);
        TambahData.setLayout(TambahDataLayout);
        TambahDataLayout.setHorizontalGroup(
            TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TambahDataLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(TambahDataLayout.createSequentialGroup()
                .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TambahDataLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(JtambahData)
                        .addGap(26, 26, 26)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TambahDataLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lStokBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lLokasiBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lPenerbutBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lPenulisBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lGenreBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lJudulBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfGenre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(tfPenulis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfPenerbit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfLokasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        TambahDataLayout.setVerticalGroup(
            TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahDataLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JtambahData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lGenreBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPenulisBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPenerbutBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lLokasiBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStokBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnTambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        listPanel.add(TambahData, "card2");

        JubahData.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JubahData.setForeground(new java.awt.Color(51, 51, 51));
        JubahData.setText("UBAH DATA");

        idUbah.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        idUbah.setText("Masukkan id data yang akan diubah");

        tfidUbah.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnidUbah.setText("Input");
        btnidUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnidUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UbahDataLayout = new javax.swing.GroupLayout(UbahData);
        UbahData.setLayout(UbahDataLayout);
        UbahDataLayout.setHorizontalGroup(
            UbahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UbahDataLayout.createSequentialGroup()
                .addGroup(UbahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UbahDataLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(JubahData))
                    .addGroup(UbahDataLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(idUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfidUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnidUbah)))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        UbahDataLayout.setVerticalGroup(
            UbahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UbahDataLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(JubahData)
                .addGap(31, 31, 31)
                .addGroup(UbahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfidUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnidUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(302, Short.MAX_VALUE))
        );

        listPanel.add(UbahData, "card3");

        btnUbahData.setText("Ubah Data");
        btnUbahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahDataActionPerformed(evt);
            }
        });

        tfStokUbah.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lStokBukuUbah.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        lStokBukuUbah.setText("Stok Buku");

        lLokasiBukuUbah.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        lLokasiBukuUbah.setText("Lokasi Buku");

        tfLokasiUbah.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        tfPenerbitUbah.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lPenerbitBukuUbah.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        lPenerbitBukuUbah.setText("Penerbit Buku");

        tfPenulisUbah.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lPenulisBukuUbah.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        lPenulisBukuUbah.setText("Penulis Buku");

        lGenreBukuUbah.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        lGenreBukuUbah.setText("Genre Buku");

        tfGenreUbah.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tfGenreUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGenreUbahActionPerformed(evt);
            }
        });

        tfJudulUbah.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lJudulBukuUbah.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        lJudulBukuUbah.setText("Judul Buku");

        JubahData1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JubahData1.setForeground(new java.awt.Color(51, 51, 51));
        JubahData1.setText("UBAH DATA");

        javax.swing.GroupLayout UbahData2Layout = new javax.swing.GroupLayout(UbahData2);
        UbahData2.setLayout(UbahData2Layout);
        UbahData2Layout.setHorizontalGroup(
            UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UbahData2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnUbahData, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(UbahData2Layout.createSequentialGroup()
                .addGroup(UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UbahData2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(JubahData1))
                    .addGroup(UbahData2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lStokBukuUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lLokasiBukuUbah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lPenerbitBukuUbah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lPenulisBukuUbah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lGenreBukuUbah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lJudulBukuUbah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfJudulUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfGenreUbah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(tfPenulisUbah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfPenerbitUbah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfLokasiUbah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfStokUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(100, 100, 100))
        );
        UbahData2Layout.setVerticalGroup(
            UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UbahData2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(JubahData1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lJudulBukuUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJudulUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lGenreBukuUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGenreUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPenulisBukuUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPenulisUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPenerbitBukuUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPenerbitUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lLokasiBukuUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLokasiUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UbahData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStokBukuUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfStokUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnUbahData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        listPanel.add(UbahData2, "card7");

        JhapusData.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JhapusData.setForeground(new java.awt.Color(51, 51, 51));
        JhapusData.setText("HAPUS DATA");

        btnidHapus.setText("Input");
        btnidHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnidHapusActionPerformed(evt);
            }
        });

        tfidHapus.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        idHapus.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        idHapus.setText("Masukkan id data yang akan dihapus");

        javax.swing.GroupLayout HapusDataLayout = new javax.swing.GroupLayout(HapusData);
        HapusData.setLayout(HapusDataLayout);
        HapusDataLayout.setHorizontalGroup(
            HapusDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HapusDataLayout.createSequentialGroup()
                .addGroup(HapusDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HapusDataLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(JhapusData))
                    .addGroup(HapusDataLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(idHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfidHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnidHapus)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        HapusDataLayout.setVerticalGroup(
            HapusDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HapusDataLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(JhapusData)
                .addGap(27, 27, 27)
                .addGroup(HapusDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfidHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnidHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(306, Short.MAX_VALUE))
        );

        listPanel.add(HapusData, "card4");

        JcariData.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JcariData.setForeground(new java.awt.Color(51, 51, 51));
        JcariData.setText("CARI DATA");

        jRadioButton1.setText("Judul Buku");

        jRadioButton2.setText("Genre Buku");

        jRadioButton3.setText("Penulis Buku");

        jRadioButton4.setText("Penerbit Buku");

        jRadioButton5.setText("Lokasi Buku");

        jRadioButton6.setText("Stok Buku");

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel1.setText("Cari Data Berdasarkan :");

        jButton1.setText("Cari");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setText("*nb : pilih satu saja, kemudian masukan kata kunci pada box di bawah ini");

        javax.swing.GroupLayout CariDataLayout = new javax.swing.GroupLayout(CariData);
        CariData.setLayout(CariDataLayout);
        CariDataLayout.setHorizontalGroup(
            CariDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CariDataLayout.createSequentialGroup()
                .addGroup(CariDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CariDataLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(JcariData))
                    .addGroup(CariDataLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(CariDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(CariDataLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CariDataLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(CariDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3))
                        .addGap(96, 96, 96)
                        .addGroup(CariDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton6))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        CariDataLayout.setVerticalGroup(
            CariDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CariDataLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(JcariData)
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(CariDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CariDataLayout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton6))
                    .addGroup(CariDataLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)))
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CariDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        listPanel.add(CariData, "card5");

        TampilData.setPreferredSize(new java.awt.Dimension(724, 436));

        JlistData1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JlistData1.setForeground(new java.awt.Color(51, 51, 51));
        JlistData1.setText("LIST DATA");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Aku", "Action", "Akulah", "Gramed", "Jakarta", "1"},
                {"2", "Aku2", "Action", "Akulah", "Gramed2", "Bandung", "2"}
            },
            new String [] {
                "ID", "Judul", "Genre", "Penulis", "Penerbit", "Lokasi", "Stok"
            }
        ));
        jTable1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTable1ComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout TampilDataLayout = new javax.swing.GroupLayout(TampilData);
        TampilData.setLayout(TampilDataLayout);
        TampilDataLayout.setHorizontalGroup(
            TampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TampilDataLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(TampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlistData1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        TampilDataLayout.setVerticalGroup(
            TampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TampilDataLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(JlistData1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        listPanel.add(TampilData, "card6");

        judulBackground.setBackground(new java.awt.Color(162, 155, 254));
        judulBackground.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        Judul.setBackground(new java.awt.Color(116, 185, 255));
        Judul.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Judul.setForeground(new java.awt.Color(102, 0, 255));
        Judul.setText("PERPUSTAKAAN PRIBADI PUNYA LATIEF");

        javax.swing.GroupLayout judulBackgroundLayout = new javax.swing.GroupLayout(judulBackground);
        judulBackground.setLayout(judulBackgroundLayout);
        judulBackgroundLayout.setHorizontalGroup(
            judulBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, judulBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        judulBackgroundLayout.setVerticalGroup(
            judulBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judulBackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(judulBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(judulBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        //remove
        listPanel.removeAll();
        listPanel.repaint();
        listPanel.revalidate();
        
        //add
        listPanel.add(UbahData);
        listPanel.repaint();
        listPanel.revalidate();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        
        //remove
        listPanel.removeAll();
        listPanel.repaint();
        listPanel.revalidate();
        
        //add
        listPanel.add(TambahData);
        listPanel.repaint();
        listPanel.revalidate();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDataActionPerformed
        // TODO add your handling code here:
        ModelForm mod = new ModelForm();
        mod.submitForm(this);
            // refresh tabel
            
    }//GEN-LAST:event_btnTambahDataActionPerformed

    private void tfGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGenreActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
        //remove
        listPanel.removeAll();
        listPanel.repaint();
        listPanel.revalidate();
        
        //add
        listPanel.add(HapusData);
        listPanel.repaint();
        listPanel.revalidate();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        
        //remove
        listPanel.removeAll();
        listPanel.repaint();
        listPanel.revalidate();
        
        //add
        listPanel.add(CariData);
        listPanel.repaint();
        listPanel.revalidate();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        // TODO add your handling code here:
         
        
        
    
        //remove
        listPanel.removeAll();
        listPanel.repaint();
        listPanel.revalidate();
        
        //add
        listPanel.add(TampilData);
        listPanel.repaint();
        listPanel.revalidate();
    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnUbahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahDataActionPerformed
        // TODO add your handling code here:
        String IdUbah = getIdUbah();
        
        try{
            String query = "UPDATE `buku` SET `id` = '"+IdUbah+"',  `judul` = '"+tfJudulUbah+"',`genre` = '"+tfGenreUbah+"', `penulis` = '"+tfPenulisUbah+"', `penerbit` = '"+tfPenerbitUbah+"', `lokasi` = '"+tfLokasiUbah+"', `stok` = '"+tfStokUbah+"' WHERE `buku`.`id` = '"+IdUbah+"' ";
            connector.statement = connector.koneksi.createStatement();
            connector.statement.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Update Berhasil !!");
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Update Gagal!!\nError: "+ex);
            }
    }//GEN-LAST:event_btnUbahDataActionPerformed

    private void tfGenreUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGenreUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGenreUbahActionPerformed

    private void btnidUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnidUbahActionPerformed
        // TODO add your handling code here:
        
        //remove
        listPanel.removeAll();
        listPanel.repaint();
        listPanel.revalidate();
        
        //add
        listPanel.add(UbahData2);
        listPanel.repaint();
        listPanel.revalidate();
    }//GEN-LAST:event_btnidUbahActionPerformed

    private void btnidHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnidHapusActionPerformed
        // TODO add your handling code here:
        String pkey = getPKey();
        try{
            
            String query = "DELETE FROM `buku` WHERE `buku`.`id` = \'"+pkey+"\'";
            // eksekusi query hapus data database
            connector.statement = connector.koneksi.createStatement();
            connector.statement.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Hapus Berhasil !!");
            // kosongkan form
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Hapus Gagal !!\n\nError: "+ex);
        }
    
    }//GEN-LAST:event_btnidHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        
        int dialogBtnKeluar = JOptionPane.YES_NO_OPTION;
        int dialogResultKeluar = JOptionPane.showConfirmDialog(this, "Anda yakin akan keluar ?", "PERINGATAN !!", dialogBtnKeluar); 
        
        if (dialogResultKeluar==0) {
            //true
            System.exit(0);
        } else {
            //false
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tfJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJudulActionPerformed

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void jTable1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTable1ComponentAdded
        // TODO add your handling code here:
       jmlData = 0;
        try{
            connector.statement = connector.koneksi.createStatement();
            String query = "Select * from `siswa`";
            ResultSet resultSet = connector.statement.executeQuery(query); //pengambilan data dalam java dari database
            while(resultSet.next()){ //ambil nilai dari baris ke 0 sampai baris akhir
                jmlData++;
            }
            return jmlData; //mengembalikan jumlah data ke readtiket
        }catch(SQLException e){
            System.out.println(e.getMessage());
            System.out.println("SQL Error");
            return 0;
        }
        
         
       String Id, Judul, Genre, Penulis, Penerbit, Lokasi, Stok;
    int jmlData;
     String data[][] = new String[500][7];
    
   // Connector connector = new Connector();    
    
    //DEKLARASI KOMPONEN
    JFrame window = new JFrame("JDBC Punya Latief");
    JTable tabel;
    DefaultTableModel tableModel;
    JScrollPane scrollPane;
    Object namaKolom[] = {"Id","Judul","Genre","Penulis","Penerbit","Lokasi","Stok"};

    
        window.setLayout(null);
        window.setSize(550,600);
      //  window.setDefaultCloseOperation(3);
        window.setVisible(true);
        window.setLocationRelativeTo(null);
        window.setResizable(false);

 
            
           
         try{
            jmlData = 0;
            String query = "Select * from `buku`"; //proses pengambilan data
            connector.statement = connector.koneksi.createStatement();
            ResultSet resultSet = connector.statement.executeQuery(query); //result isinya tabel belum berupa string
            while(resultSet.next()){ //konversi tabel ke string
                data[jmlData][0] = resultSet.getString("id"); 
                data[jmlData][1] = resultSet.getString("judul");
                data[jmlData][2] = resultSet.getString("genre");
                data[jmlData][3] = resultSet.getString("penulis");
                data[jmlData][5] = resultSet.getString("penerbit");
                data[jmlData][6] = resultSet.getString("lokasi");
                data[jmlData][7] = resultSet.getString("stok");
                jmlData++; 
            }
            connector.statement.close();
        }catch(SQLException e){
            System.out.println(e.getMessage());
            System.out.println("SQL Error");
        }
        
        tabel = new JTable(data,namaKolom);
        scrollPane = new JScrollPane(tabel);
        window.add(scrollPane);
        
        scrollPane.setBounds(20, 35, 500, 300);
        scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
    }//GEN-LAST:event_jTable1ComponentAdded

    /**
     * @param args the command line arguments
     */
    
    //ubah
    public String getIdUbah(){    // getter pkey untuk penanda primary key data database yang akan dihapus
        return tfidUbah.getText();
    }
    public String getJudulUbah(){
        return tfJudulUbah.getText();
    }
    public String getGenreUbah(){
        return tfGenreUbah.getText();
    }
    public String getPenulisUbah(){
        return tfPenulisUbah.getText();
    }
    public String getPenerbitUbah(){
        return tfPenerbitUbah.getText();
    }
    public String getLokasiUbah(){
        return tfLokasiUbah.getText();
    }
    public String getStokUbah(){
        return tfStokUbah.getText();
    }
    
    //hapus
    public String  getPKey(){    // getter pkey untuk penanda primary key data database yang akan dihapus
        return tfidHapus.getText();
    }
    
    //tambah
    public String getId(){    // getter pkey untuk penanda primary key data database yang akan dihapus
        return tfId.getText();
    }
    public String getJudul(){
        return tfJudul.getText();
    }
    public String getGenre(){
        return tfGenre.getText();
    }
    public String getPenulis(){
        return tfPenulis.getText();
    }
    public String getPenerbit(){
        return tfPenerbit.getText();
    }
    public String getLokasi(){
        return tfLokasi.getText();
    }
    public String getStok(){
        return tfStok.getText();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CariData;
    private javax.swing.JPanel HapusData;
    private javax.swing.JLabel JcariData;
    private javax.swing.JLabel JhapusData;
    private javax.swing.JLabel JlistData1;
    private javax.swing.JLabel JtambahData;
    private javax.swing.JLabel JubahData;
    private javax.swing.JLabel JubahData1;
    private javax.swing.JLabel Judul;
    private javax.swing.JPanel TambahData;
    private javax.swing.JPanel TampilData;
    private javax.swing.JPanel UbahData;
    private javax.swing.JPanel UbahData2;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahData;
    private javax.swing.JButton btnTampil;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnUbahData;
    private javax.swing.JButton btnidHapus;
    private javax.swing.JButton btnidUbah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel idHapus;
    private javax.swing.JLabel idUbah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel judulBackground;
    private javax.swing.JLabel lGenreBuku;
    private javax.swing.JLabel lGenreBukuUbah;
    private javax.swing.JLabel lJudulBuku;
    private javax.swing.JLabel lJudulBukuUbah;
    private javax.swing.JLabel lLokasiBuku;
    private javax.swing.JLabel lLokasiBukuUbah;
    private javax.swing.JLabel lPenerbitBukuUbah;
    private javax.swing.JLabel lPenerbutBuku;
    private javax.swing.JLabel lPenulisBuku;
    private javax.swing.JLabel lPenulisBukuUbah;
    private javax.swing.JLabel lStokBuku;
    private javax.swing.JLabel lStokBukuUbah;
    private javax.swing.JPanel listPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField tfGenre;
    private javax.swing.JTextField tfGenreUbah;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfJudul;
    private javax.swing.JTextField tfJudulUbah;
    private javax.swing.JTextField tfLokasi;
    private javax.swing.JTextField tfLokasiUbah;
    private javax.swing.JTextField tfPenerbit;
    private javax.swing.JTextField tfPenerbitUbah;
    private javax.swing.JTextField tfPenulis;
    private javax.swing.JTextField tfPenulisUbah;
    private javax.swing.JTextField tfStok;
    private javax.swing.JTextField tfStokUbah;
    private javax.swing.JTextField tfidHapus;
    private javax.swing.JTextField tfidUbah;
    // End of variables declaration//GEN-END:variables
}
